### PR TITLE
WIP: putImageData support

### PR DESCRIPTION
**Pull request by ziks21**

### CODE REVIEW

**Comment by volodymyrlut** [comment]
Guys, do you need any help here? Any ideas, how I can help you to have this deployed?

**Comment by iddan** [comment]
This was done a long time ago but if I remember correctly it didn't worked yet. You can test if it does and fix if needed

**Comment by iddan** [comment]
Nothing has changed yet. I would love to accept a fully working PR though.

**Comment by hmajid2301** [comment]
Ok I'll take a look at it and see what I can manage.

**Pull request closed without merging**
