### PR TITLE
Fix autoScale

### PR DESCRIPTION
**Pull request by cj3g10**
#48
Resolved issue where autoScale will double the canvas width or height if setting the canvas width and height.

### CODE REVIEW

**Comment by iddan** [comment]
Can you explain the changes?

**Comment by cj3g10** [comment]
As mentioned in the issue, autoScale() is called when the canvas' width or height is set.
So autoScale() is called when you set the width, then is called again when you set the height. Therefore the width will be scaled twice (and vice versa if you set height before width).

The changes fix it so that calling autoScale() again will not re-scale the already scaled canvas.

**Comment by iddan** [comment]
Oh, I see - awesome!

**Comment by iddan** [comment]
Will publish it once I have a moment

**Pull request merged**
