### PR TITLE
Add yarn to dev dependencies

### PR DESCRIPTION
**Pull request by MidnightJava**
npm install failed because the yarn dependency was not specified in package.json

### CODE REVIEW

**Comment by iddan** [comment]
Thank you for your contribution. What problem does this PR aims to solve?

**Comment by MidnightJava** [comment]
See edited original comment. I believe I should have added yarn as a regular dependency, not a dev dependency, however.

**Comment by iddan** [comment]
Cant reproduce the issue

**Comment by MidnightJava** [comment]
Here's what I get when I install without the mod. Is the assumption that yarn is installed as a global module?

```
$ npm install

> react-native-canvas@0.1.15 prepare /opt/git/axios-dev/react-native-sigplot/node_modules/react-native-canvas
> yarn build

sh: yarn: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-native-canvas@0.1.15 prepare: `yarn build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-native-canvas@0.1.15 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /nishome/maleone/.npm/_logs/2017-09-29T19_56_08_193Z-debug.log

```

**Comment by iddan** [comment]
You need the yarn package manager installed globally see: https://yarnpkg.com/en/docs/install

**Pull request closed without merging**
