### PR TITLE
WIP: Move default width and height to Canvas component

### PR DESCRIPTION
**Pull request by iegik**
**Problem**:
With `webviewProperties` decorator always have passed default values to the canvas wrapper (`View`), which is not equal of canvas size.

```javascript
const handleCanvas = (canvas) => {
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = 'purple';
    console.log(canvas.width, canvas.height)
    ctx.fillRect(0, 0, canvas.width, canvas.height);
};
...
<Canvas ref={handleCanvas} {...{width: 300, height: 400, style: {width: 300, height: 400}}}/>
```

**Solution**:
Moved default size values (300x150) to constructor
Possible solution for https://github.com/iddan/react-native-canvas/issues/48

**Result**:
```
<Canvas ref={handleCanvas} {...{width: 400, height: 200, style: {width: 400, height: 200}}}/>
```

### CODE REVIEW

**Comment by iddan** [comment]
Hey there, Thanks for contributing and nice catch! We try to follow the DOM canvas API as much as possible so passing width and height in the constructor is not preferable. Would leaving only the assignments work for you?

```javascript
constructor() {
    this.width = 300;
    this.height = 150;
}
```

**Comment by iegik** [comment]
Em... Canvas constructor is already takes width and height from props. In left corner You can see html `<canvas />` whitch takes same properties:

```
export class Canvas extends Component {
    constructor({onRender}) {
        super();
        this.ref = onRender;
    }
    componentDidMount() {
        this.ref(this.refs.canvas);
    }
    componentDidUpdate() {
        this.ref(this.refs.canvas);
    }
    render() {
        const {onRender, style = {}, width = style.width || 100, height = style.height || 100, ...rest} = this.props;
        return <canvas ref="canvas" {...{width, height, style: {width, height,...style}, ...rest}}/>
    }
}
```

P.S.: I replace `ref` with `onRender` for taking `handleCanvas`.

Unfortunately, solution has still wrong: webView not same size or same ratio.

**Comment by iegik** [comment]
`<canvas/>` works same as `` - if you pass with and height - it tries to get ratio from that attributes. If you pass `style` attribute, it streches to that size.

**Comment by iddan** [comment]
What do we see in the picture?

**Comment by iegik** [comment]
Sorry, i didn\`t comment the picture. Here we can see, how I select region with canvas with "unicorn". I think, webview`s iframe has static default size, and did not change, when canvas size changes.

I did not find how iframe of webview can be changed dynamically.

**Comment by iegik** [comment]
Also I notice, that autoscale-canvas has dependency on canvas.size
```
    canvas.style.width = canvas.width + 'px';
    canvas.style.height = canvas.height + 'px';
```

So, there is relationship between `canvas.width` and `canvas.style.width`

**Comment by iegik** [comment]
This is index.html opened in browser. Here is blank `canvas` with default size: 300x150.

**Comment by iegik** [comment]
No, there is another problem.


Now, sizes of purple rectangle is correct, but other items has broken. I\`m stuck.

**Comment by iddan** [comment]
I don't see any progress with this PR and I think this issue is resolved through the last issues and PRs. Let me know if you think differently.

**Pull request closed without merging**
